name: CI

on:
  push:
    branches: [ main]

  pull_request:
    branches: [ main]

jobs:
  mac-setup:
    name: Test e2e.sh
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: MacOS Pre Checks - After Setup
        shell: bash
        run: |
            ./assist.sh pre-checks

      - name: MacOS Speed Test using Docker - After Setup
        shell: bash
        run: |
            ./assist.sh speed-test

      - name: MacOS Teardown
        shell: bash
        run: |
            ./assist.sh teardown

      - name: MacOS Setup
        shell: bash
        run: |
            ./assist.sh setup

      - name: MacOS Setup - Tests
        shell: bash
        run: |
            ./assist.sh test


